apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/media/config/radarr
    type: DirectoryOrCreate
