apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - data-namespace.yaml
  - media-namespaces.yaml
  - observability-namespace.yaml
  - pipelines-namespaces.yaml
  - serving-namespaces.yaml
  - tailscale-namespace.yaml