apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - data-namespace.yaml
  - media-namespace.yaml
  - observability-namespace.yaml
  - platform-namespace.yaml
  - pipelines-namespace.yaml
  - serving-namespace.yaml
  - tailscale-namespace.yaml
