apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - mkdir-media-dirs-job.yaml
  - media-library-movies-pv.yaml
  - media-library-movies-pvc.yaml
  - media-library-tv-pv.yaml
  - media-library-tv-pvc.yaml
  - media-downloads-pv.yaml
  - media-downloads-pvc.yaml
