apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: media-downloads-pv

