apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-tv-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/media/library/tv
  claimRef:
    namespace: media
    name: media-library-tv
