apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/media/downloads/
    type: DirectoryOrCreate
  claimRef:
    namespace: media
    name: media-downloads
