apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-movies-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/local/media/library/movies
  claimRef:
    namespace: media
    name: media-library-movies
